sudo: required

language: node_js
node_js:
  - "4.1"

git:
  depth: 1

services:
  - docker

before_install:  
  - docker build -t auser/travis .
  - docker run -d -p "127.0.0.1:80:8080" auser/travis 
  - docker ps -a

script:
  - npm start
