sudo: required

language: node_js
node_js:
  - "4.1"

git:
  depth: 1

services:
  - docker

before_install:  
  - docker build -t auser/travis .
  - docker run --rm --it -p "80:8080" auser/travis 

script:
  - npm start
